version: '3.1'

services:

  ewm-service:
    build: main/
    container_name: main
    image: 'explore-with-me-main'
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - ewm-stat.url=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ExploreWithMe
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  ewm-db:
    container_name: ewm-db
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ExploreWithMe
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root

  stats-server:
    build: stats/
    container_name: stats
    image: 'explore-with-me-stat'
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ExploreWithMeStats
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  stats-db:
    container_name: stats-db
    image: postgres:14-alpine
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=ExploreWithMeStats
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root